# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. How to import `NumPy` library?** 

In [1]:
import numpy as np


**2. Convert the given Python list into NumPy array and check its data type**

In [2]:
list_1 = [1,2,3,4,5]

In [3]:
my_array = np.array(list_1)
my_array, type(my_array)


(array([1, 2, 3, 4, 5]), numpy.ndarray)

**3. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [4]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

**4. Generate an `array of "5" zeros`**

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**5. Generate the following `matrix`.**

In [8]:
# To avoid overwriting the output, please code here 
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**6. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [9]:
# To avoid overwriting the output, please code here 
np.ones(5)


array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**7. Generate an array of "5" tens.**

In [10]:
# To avoid overwriting the output, please code here 
np.ones(5) * 10


array([10., 10., 10., 10., 10.])

array([ 10.,  10.,  10.,  10.,  10.])

**8. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [11]:
# To avoid overwriting the output, please code here 
np.arange(52, 100, 2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**9. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [12]:
# To avoid overwriting the output, please code here 
np.linspace(0, 1, 10, retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**10. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [14]:
# To avoid overwriting the output, please code here 
vector_arr = np.arange(25)


In [15]:
# Generating vector array
vector_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
# To avoid overwriting the output, please code here 
matrix_reshape = vector_arr.reshape(5, 5)

In [17]:
# reshape to convert into 2-d
matrix_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# To avoid overwriting the output, please code here 

In [18]:
# Using shape
vector_arr.shape = (5, 5)
vector_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**11. How to generate a single random number using NumPy built-in function?**

In [19]:
# To avoid overwriting the output, please code here 
np.random.rand(1)

array([0.50750615])

array([ 0.55509608])

**12. Write a code to generate a 7x5 matrix of 35 random numbers?** <br>
*Notice, there are no ( ) in the output matrix!*

In [20]:
# To avoid overwriting the output, please code here 
print(np.random.rand(7, 5))

[[0.277837   0.44482565 0.57210001 0.93292626 0.03890292]
 [0.06973716 0.77317073 0.73887154 0.63170881 0.43956782]
 [0.22273573 0.89469169 0.46077405 0.32399745 0.72875721]
 [0.39126344 0.05087485 0.78519323 0.70592076 0.24859131]
 [0.52845905 0.73047992 0.55986922 0.29950338 0.70039757]
 [0.30718882 0.5105594  0.73387556 0.21366572 0.48181321]
 [0.15927091 0.50904786 0.20725002 0.81351032 0.57837012]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**13. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [21]:
# To avoid overwriting the output, please code here 
np.eye(5) * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

**14. Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [22]:
#18a:
# To avoid overwriting the output, please code here 
array_2d = np.arange(30).reshape(6, 5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

**15. Can you calculate the sum of all the numbers in array_2d?**

In [23]:
# To avoid overwriting the output, please code here 
array_2d.sum()

np.int64(435)

435

**16. Calculate sum of all the rows and columns in array_2d.**

In [24]:
# To avoid overwriting the output, please code here 
print(f"Row sum: {array_2d.sum(axis=1)}")
print(f"Columns sum: {array_2d.sum(axis=0)}")

Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


**17. Calculate the standard deviation of the values in array_2d.**

In [25]:
# To avoid overwriting the output, please code here 
array_2d.std()

np.float64(8.65544144839919)

8.6554414483991895

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 